service: bgg-picker
frameworkVersion: ">= 4.3.0"
useDotenv: true
provider:
  name: aws
  runtime: provided.al2
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}

functions:
  api:
    memorySize: 3008
    timeout: 10
    handler: bin/main
    events:
      - http:
          path: /
          method: GET

package:
  patterns:
    - bin/*
